services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: moneyflow
      POSTGRES_PASSWORD: moneyflow_password
      POSTGRES_DB: moneyflow_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  db_data: