services:
  db:
    image: postgres
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: moneyflow1
      POSTGRES_PASSWORD: moneyflow_password1
      POSTGRES_DB: moneyflow_db1
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always


volumes:
  db_data: